'use client';
import {createContext,useCallback,useContext,useEffect,useState,type ReactNode} from 'react';
import {Sun,Moon,Globe,Check} from 'lucide-react';
import {DropdownMenu,DropdownMenuItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {IOSDropdownMenuContent as DropdownMenuContent} from './ios-overlays';
import {languages,parsePreferences,storageKey,translate,type Locale,type Theme} from './i18n';
type Preferences={locale:Locale;theme:Theme;setLocale:(v:Locale)=>void;setTheme:(v:Theme)=>void;t:<T>(value:T)=>T};
const Context=createContext<Preferences|null>(null);
export function PreferencesProvider({children}:{children:ReactNode}){const [locale,setLocale]=useState<Locale>('ru'),[theme,setTheme]=useState<Theme>('dark'),[ready,setReady]=useState(false);
useEffect(()=>{try{const p=parsePreferences(localStorage.getItem(storageKey));setLocale(p.locale);setTheme(p.theme)}catch{}setReady(true);const sync=(e:StorageEvent)=>{if(e.key===storageKey){const p=parsePreferences(e.newValue);setLocale(p.locale);setTheme(p.theme)}};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[]);
useEffect(()=>{if(!ready)return;document.documentElement.classList.toggle('dark',theme==='dark');document.documentElement.dataset.theme=theme;document.documentElement.lang=languages.find(x=>x.id===locale)!.tag;document.documentElement.style.colorScheme=theme;try{localStorage.setItem(storageKey,JSON.stringify({locale,theme}))}catch{}},[locale,theme,ready]);
const t=useCallback(<T,>(value:T):T=>typeof value==='string'?translate(value,locale) as T:value,[locale]);return <Context.Provider value={{locale,theme,setLocale,setTheme,t}}>{children}</Context.Provider>}
export function usePreferences(){const context=useContext(Context);if(!context)throw Error('PreferencesProvider missing');return context}
export function AppearanceControls(){const {locale,theme,setLocale,setTheme,t}=usePreferences();return <div className="appearance-controls"><DropdownMenu><DropdownMenuTrigger className="language-trigger" aria-label={t('Язык приложения')}><Globe size={18}/><span>{locale==='zh'?'中文':locale.toUpperCase()}</span></DropdownMenuTrigger><DropdownMenuContent className="language-dropdown">{languages.map(lang=><DropdownMenuItem key={lang.id} onClick={()=>setLocale(lang.id)} className="language-item"><span lang={lang.tag}>{lang.native}</span><small>{t(lang.label)}</small>{locale===lang.id&&<Check size={16}/>}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><button className="icon-button theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={t(theme==='dark'?'Включить светлую тему':'Включить тёмную тему')} title={t(theme==='dark'?'Светлая тема':'Тёмная тема')}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button></div>}
export function LanguageOptions(){const {locale,setLocale,t}=usePreferences();return <div className="language-options">{languages.map(lang=><button key={lang.id} aria-pressed={locale===lang.id} onClick={()=>setLocale(lang.id)} className={'language-option '+(locale===lang.id?'chosen':'')}><Globe size={20}/><span><b lang={lang.tag}>{lang.native}</b><small>{t(lang.label)}</small></span>{locale===lang.id&&<Check size={20}/>}</button>)}</div>}
export function ThemeOptions(){const {theme,setTheme,t}=usePreferences();return <div className="theme-options">{(['light','dark'] as Theme[]).map(item=><button key={item} className={'theme-choice '+(theme===item?'chosen':'')} aria-pressed={theme===item} onClick={()=>setTheme(item)}><div className={'theme-swatch swatch-'+item}><div className="swatch-top"><i/><span/><i/></div><div className="swatch-hero"/><div className="swatch-cards"><i/><i/></div></div><div className="theme-label">{item==='light'?<Sun size={17}/>:<Moon size={17}/>}<span>{t(item==='light'?'Светлая тема':'Тёмная тема')}</span>{theme===item&&<Check size={17}/>}</div></button>)}</div>}
