'use client';
import {createContext,useCallback,useContext,useEffect,useState,type ReactNode} from 'react';
import {Sun,Moon,Globe,Check,Smartphone} from 'lucide-react';
import {DropdownMenu,DropdownMenuItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {IOSDropdownMenuContent as DropdownMenuContent} from './ios-overlays';
import {languages,parsePreferences,resolveTheme,storageKey,translate,type Locale,type Theme} from './i18n';
type Preferences={locale:Locale;theme:Theme;resolvedTheme:'light'|'dark';setLocale:(v:Locale)=>void;setTheme:(v:Theme)=>void;t:<T>(value:T)=>T};
const Context=createContext<Preferences|null>(null);
export function PreferencesProvider({children}:{children:ReactNode}){const [locale,setLocale]=useState<Locale>('ru'),[theme,setTheme]=useState<Theme>('system'),[ready,setReady]=useState(false);
const [systemDark,setSystemDark]=useState(true);
const resolvedTheme=resolveTheme(theme,systemDark);
useEffect(()=>{const media=window.matchMedia('(prefers-color-scheme: dark)');const update=()=>setSystemDark(media.matches);update();media.addEventListener('change',update);return()=>media.removeEventListener('change',update)},[]);
useEffect(()=>{try{const p=parsePreferences(localStorage.getItem(storageKey));setLocale(p.locale);setTheme(p.theme)}catch{}setReady(true);const sync=(e:StorageEvent)=>{if(e.key===storageKey){const p=parsePreferences(e.newValue);setLocale(p.locale);setTheme(p.theme)}};window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[]);
useEffect(()=>{if(!ready)return;document.documentElement.classList.toggle('dark',resolvedTheme==='dark');document.documentElement.dataset.theme=resolvedTheme;document.documentElement.lang=languages.find(x=>x.id===locale)!.tag;document.documentElement.style.colorScheme=resolvedTheme;try{localStorage.setItem(storageKey,JSON.stringify({locale,theme}))}catch{}},[locale,theme,resolvedTheme,ready]);
const t=useCallback(<T,>(value:T):T=>typeof value==='string'?translate(value,locale) as T:value,[locale]);return <Context.Provider value={{locale,theme,resolvedTheme,setLocale,setTheme,t}}>{children}</Context.Provider>}
export function usePreferences(){const context=useContext(Context);if(!context)throw Error('PreferencesProvider missing');return context}
export function AppearanceControls(){const {locale,resolvedTheme:theme,setLocale,setTheme,t}=usePreferences();return <div className="appearance-controls"><DropdownMenu><DropdownMenuTrigger className="language-trigger" aria-label={t('Язык приложения')}><Globe size={18}/><span>{locale==='zh'?'中文':locale.toUpperCase()}</span></DropdownMenuTrigger><DropdownMenuContent className="language-dropdown">{languages.map(lang=><DropdownMenuItem key={lang.id} onClick={()=>setLocale(lang.id)} className="language-item"><span lang={lang.tag}>{lang.native}</span><small>{t(lang.label)}</small>{locale===lang.id&&<Check size={16}/>}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><button className="icon-button theme-toggle" onClick={()=>setTheme(theme==='dark'?'light':'dark')} aria-label={t(theme==='dark'?'Включить светлую тему':'Включить тёмную тему')} title={t(theme==='dark'?'Светлая тема':'Тёмная тема')}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button></div>}
export function LanguageOptions(){const {locale,setLocale,t}=usePreferences();return <div className="language-options">{languages.map(lang=><button key={lang.id} aria-pressed={locale===lang.id} onClick={()=>setLocale(lang.id)} className={'language-option '+(locale===lang.id?'chosen':'')}><Globe size={20}/><span><b lang={lang.tag}>{lang.native}</b><small>{t(lang.label)}</small></span>{locale===lang.id&&<Check size={20}/>}</button>)}</div>}
export function ThemeOptions(){const {theme,setTheme,t}=usePreferences();return <div className="native-theme-options">{(['system','light','dark'] as Theme[]).map(item=><button key={item} className={'native-theme-row '+(theme===item?'chosen':'')} aria-pressed={theme===item} onClick={()=>setTheme(item)}>{item==='system'?<Smartphone size={21}/>:item==='light'?<Sun size={21}/>:<Moon size={21}/>}<span>{t(item==='system'?'Системная':item==='light'?'Светлая':'Тёмная')}</span>{theme===item&&<Check size={20}/>}</button>)}<p>{t('Системная тема следует настройкам устройства')}</p></div>}
